### ISSUE TITLE
When scaffolding a new plugin, the default "icon" value is blank, causing the block to error out.

### ISSUE THREAD

**Issue by AdamWills** [ryanwelcher/create-block-multple-blocks-template#2]
The end result of a scaffolded block.json includes:

```json
    ...
   "icon": "",
   ...
```

This produces the following error:
> The icon passed is invalid. The icon should be a string, an element, a function, or an object following the specifications documented in https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#icon-optional

Easy enough to fix afterwards, but a better default might be needed.

**Comment by ryanwelcher** [comment]
Great catch @AdamWills! I'll get that updated - unless you want to do a PR?

**Comment by AdamWills** [comment]
Happy to do a PR - what is the end result that you would want - leaving "icon" out? Or defining a default icon?

**Comment by ryanwelcher** [comment]
Let's go with leaving the icon out.
